### ISSUE TITLE
Fixing Channels has no effect

### ISSUE THREAD

**Issue by Fr33man85** [lexlix/FPV-Video-Channelsorter-5.8GHz#5]
Hi,
the issue is, that you can fix a channel by ticking in the "fixed" slider and choose a channel, but the channel will not be used by the calculations and is also not displayed in the channel infos on the left

![image](https://user-images.githubusercontent.com/50385199/179845015-d9193b73-34c2-40db-9b7a-39bf3d91bded.png)

I tryed to figure it out in android Studio, but my knowledge is still not enough to bugfix this.

greetings

**Comment by lexlix** [comment]
Bug is fixed. New version will be deployed to the Play Store today.

**Comment by Fr33man85** [comment]
i build and tested it. looks great! Many thanks for your effort :D

**Comment by Fr33man85** [comment]
something what is not necessary but would be a "nice to have": if accidentally selected two same fixed frequencies, change background color of affected pilots "box" or show a exclamation mark.

**Comment by lexlix** [comment]
> i build and tested it. looks great! Many thanks for your effort :D

No problem always happy when people can get use out of my app :) Also already deployed to to the Play Store but it will take a few hours for the update to be available.

**Comment by lexlix** [comment]
> something what is not necessary but would be a "nice to have": if accidentally selected two same fixed frequencies, change background color of affected pilots "box" or show a exclamation mark.

Sounds like a good idea. Might look into it when I got the time. Right now it displays the min distance as 0. Might also color that red
